<?php

/**
 * @file
 * Contains cabinetry_core.module.
 */

use Drupal\Core\Url;
use Drupal\node\Entity\Node;

/**
 * Build a list of sheet packing algorithms and classes for the type selector.
 *
 * @return array
 *   An associative array containing a list of classes and labels as keys and
 *   values of sheet packing algorithms.
 */
function _cabinetry_core_sheet_packer_types() {
  $data = [
    'types' => [
      'Drupal\cabinetry_core\Cabinetry\Packer\ShelfFFPacker' => 'SHELF-FF',
    ],
  ];
  \Drupal::moduleHandler()->alter('cabinetry_sheet_packer', $data);
  return $data['types'];
}
