<?php
/**
 * @file
 * Code for the Cabinetry Cabinet Project feature.
 */
define('CABINETRY_CORE_MM3_TO_BOARDFEET', 4.23776e-7);

/**
 * Bootstrap cabinetry_core object classes.
 */
function _cabinetry_core_bootstrap() {
  spl_autoload_register(function ($class_name) {
    $filename = DRUPAL_ROOT . '/' . drupal_get_path('module', 'cabinetry_core') . "/includes/Cabinetry/$class_name.inc";
    if (file_exists($filename)) {
      include "$filename";
    }
  });
}

/**
 * Instantiate a CabinetrySheetGood from a cabinetry_sheet_goods tid.
 *
 * @param int $tid
 *   The tid to query.
 *
 * @return object
 *   Returns a CabinetrySheetGood object populated from $tid.
 */
function _cabinetry_core_load_sheet_good_object($tid) {
  return new CabinetrySheetGood(
    _cabinetry_core_get_term_field($tid, 'name'),
    (float) _cabinetry_core_get_term_field($tid, 'field_cabinetry_thickness'),
    (float) _cabinetry_core_get_term_field($tid, 'field_cabinetry_width'),
    (float) _cabinetry_core_get_term_field($tid, 'field_cabinetry_height'),
    (float) _cabinetry_core_get_term_field($tid, 'field_cabinetry_item_cost'),
    (bool) _cabinetry_core_get_term_field($tid, 'field_cabinetry_preserve_grain')
  );
}

/**
 * Instantiate a CabinetrySolidWood from a cabinetry_solid_wood tid.
 *
 * @param int $tid
 *   The tid to query.
 *
 * @return object
 *   Returns a CabinetrySheetGood object populated from $tid.
 */
function _cabinetry_core_load_solid_wood_object($tid) {
  return new CabinetrySolidWood(
    _cabinetry_core_get_term_field($tid, 'name'),
    (float) _cabinetry_core_get_term_field($tid, 'field_cabinetry_thickness'),
    (float) _cabinetry_core_get_term_field($tid, 'field_cabinetry_height'),
    0.0,
    (float) _cabinetry_core_get_term_field($tid, 'field_cabinetry_item_cost')
  );
}

/**
 * Obtain a field value from a taxonomy term.
 *
 * @param int $tid
 *   The tid to query.
 * @param string $field_name
 *   The field name to return the value from.
 *
 * @return string
 *   Returns the value of $field_name, or NULL if empty/unset.
 */
function _cabinetry_core_get_term_field($tid, $field_name) {
  $term_wrapper = entity_metadata_wrapper('taxonomy_term', taxonomy_term_load($tid));
  if (!empty($term_wrapper->$field_name->value())) {
    return $term_wrapper->$field_name->value();
  }
  return NULL;
}

/**
 * Instantiate CabinetryHardwareItem from cabinetry_hinges/cabinetry_hinge_plates.
 *
 * @param int $tid
 *   The tid to query.
 *
 * @return object
 *   Returns a CabinetrySheetGood object populated from $tid.
 */
function _cabinetry_core_load_hardware_object($tid) {
  return new CabinetryHardwareItem(
    _cabinetry_core_get_term_field($tid, 'name'),
    (float) _cabinetry_core_get_term_field($tid, 'field_cabinetry_item_cost')
  );
}
