<?php
/**
 * @file
 * Code for the Cabinetry Cabinet Project feature.
 */

include_once 'cabinetry_cabinet_project.features.inc';

define('CABINETRY_CABINET_PROJECT_THIRTY_TWO_UNIT_SIZE', 32.0);

/**
 * Implements hook_form_FORM_ID_alter().
 */
function cabinetry_cabinet_project_form_cabinetry_cabinet_project_node_form_alter(&$form, &$form_state, $form_id) {
  $form['#validate'][] = 'cabinetry_cabinet_project_validate_cabinet_dimensions';
  $form['#validate'][] = 'cabinetry_cabinet_project_validate_thirty_two_system';
  $form['#validate'][] = 'cabinetry_cabinet_project_validate_division_ratio';
  $form['#submit'][] = 'cabinetry_cabinet_project_generate_cut_list';
}

/**
 * Validation handler for cabinetry_cabinet_project_form_cabinetry_cabinet_project_node_form.
 *
 * If width, height of depth are not units of 32, then reject those fields and
 * set a form error.
 */
function cabinetry_cabinet_project_validate_thirty_two_system(&$form, &$form_state) {
  if ($form_state['values']['field_cabinetry_enforce_32mm'][LANGUAGE_NONE][0]['value'] == '1') {
    require_once 'includes/utilities.inc';

    foreach ($form_state['values']['field_cabinetry_project_componen'][LANGUAGE_NONE] as $component_index => $cabinet_component) {
      if (is_numeric($component_index)) {
        foreach (array('field_cabinetry_width', 'field_cabinetry_height', 'field_cabinetry_depth') as $audit_field) {
          if (
            !empty($cabinet_component[$audit_field][LANGUAGE_NONE][0]['value']) &&
            !_cabinetry_cabinet_project_float_evenly_divisible($cabinet_component[$audit_field][LANGUAGE_NONE][0]['value'], CABINETRY_CABINET_PROJECT_THIRTY_TWO_UNIT_SIZE)
          ) {
            form_set_error(
              'field_cabinetry_project_componen][' . LANGUAGE_NONE . '][' . $component_index . '][' . $audit_field . '][' . LANGUAGE_NONE . '][0',
              t(
                'The @field_label value of Component @component_index [@value] is not evenly divisible by 32.0',
                array(
                  '@component_index' => $component_index,
                  '@field_label' => $form['field_cabinetry_project_componen'][LANGUAGE_NONE][$component_index][$audit_field][LANGUAGE_NONE][0]['value']['#title'],
                  '@value' => $cabinet_component[$audit_field][LANGUAGE_NONE][0]['value'],
                )
              )
            );
          }
        }
      }
    }
  }
}

/**
 * Validation handler for cabinetry_cabinet_project_form_cabinetry_cabinet_project_node_form.
 *
 * Ensure width, height of depth are set for each component.
 */
function cabinetry_cabinet_project_validate_cabinet_dimensions(&$form, &$form_state) {
  require_once 'includes/utilities.inc';
  foreach ($form_state['values']['field_cabinetry_project_componen'][LANGUAGE_NONE] as $component_index => $cabinet_component) {
    if (is_numeric($component_index)) {
      foreach (array('field_cabinetry_width', 'field_cabinetry_height', 'field_cabinetry_depth') as $audit_field) {
        if (
          empty($cabinet_component[$audit_field][LANGUAGE_NONE][0]['value']) ||
          !is_numeric($cabinet_component[$audit_field][LANGUAGE_NONE][0]['value']) ||
          $cabinet_component[$audit_field][LANGUAGE_NONE][0]['value'] < 0
        ) {
          form_set_error(
            'field_cabinetry_project_componen][' . LANGUAGE_NONE . '][' . $component_index . '][' . $audit_field . '][' . LANGUAGE_NONE . '][0',
            t(
              'The @field_label value of Component @component_index is not a positive decimal number.',
              array(
                '@audit_field' => $audit_field,
                '@component_index' => $component_index,
                '@field_label' => $form['field_cabinetry_project_componen'][LANGUAGE_NONE][$component_index][$audit_field][LANGUAGE_NONE][0]['value']['#title'],
              )
            )
          );
        }
      }
    }
  }
}

/**
 * Validation handler for cabinetry_cabinet_project_form_cabinetry_cabinet_project_node_form.
 *
 * Audit division ratios.
 */
function cabinetry_cabinet_project_validate_division_ratio(&$form, &$form_state) {
  require_once 'includes/utilities.inc';
  $division_ratio_sum = 0.0;
  foreach ($form_state['values']['field_cabinetry_project_componen'][LANGUAGE_NONE] as $component_index => $cabinet_component) {
    if (is_numeric($component_index)) {
      foreach ($cabinet_component['field_cabinetry_carcass_division'][LANGUAGE_NONE][0]['field_cabinetry_division_ratio'][LANGUAGE_NONE] as $division_index => $division_ratio) {
        if (!empty($division_ratio['value'])) {
          $division_ratio_sum += (float) $division_ratio['value'];

          if ($form_state['values']['field_cabinetry_enforce_32mm'][LANGUAGE_NONE][0]['value'] == '1') {
            if (!empty($form_state['values']['field_cabinetry_project_componen'][LANGUAGE_NONE][$component_index]['field_cabinetry_height'][LANGUAGE_NONE][0]['value'])) {
              $section_height = (float) $cabinet_component['field_cabinetry_height'][LANGUAGE_NONE][0]['value'] * (float) $division_ratio['value'];
              $section_height = round($section_height, 1);
              if (!_cabinetry_cabinet_project_float_evenly_divisible($section_height, CABINETRY_CABINET_PROJECT_THIRTY_TWO_UNIT_SIZE)) {
                form_set_error(
                  'field_cabinetry_project_componen][' . LANGUAGE_NONE . '][' . $component_index . '][field_cabinetry_carcass_division][' . LANGUAGE_NONE . '][0][field_cabinetry_division_ratio][' . LANGUAGE_NONE . '][' . $division_index,
                  t(
                    '@field_label @division_id of Component @component_index of does not evenly divide by 32, and Enforce 32 is enabled.',
                    array(
                      '@component_index' => $component_index,
                      '@division_id' => $division_index,
                      '@field_label' => $form['field_cabinetry_project_componen'][LANGUAGE_NONE][$component_index]['field_cabinetry_carcass_division'][LANGUAGE_NONE][0]['#title'],
                    )
                  )
                );
              }
            }
          }

        }
      }
      if ($division_ratio_sum != 1.0) {
        form_set_error(
          'field_cabinetry_project_componen][' . LANGUAGE_NONE . '][' . $component_index . '][field_cabinetry_carcass_division',
          t(
            'The sum of the @field_label elements of Component @component_index is not 1.0.',
            array(
              '@component_index' => $component_index,
              '@field_label' => $form['field_cabinetry_project_componen'][LANGUAGE_NONE][$component_index]['field_cabinetry_carcass_division'][LANGUAGE_NONE][0]['#title'],
            )
          )
        );
      }
    }
  }
}

/**
 * Callback : Form submit handler for cabinetry_cabinet_project node form.
 *
 * @see cabinetry_cabinet_project_validate_cabinet_dimensions()
 * @see cabinetry_cabinet_project_validate_thirty_two_system()
 */
function cabinetry_cabinet_project_generate_cut_list(&$form, &$form_state) {
  _cabinetry_core_bootstrap();
  _cabinetry_cabinet_project_bootstrap();
  $project = new CabinetryCabinetProject();

  foreach ($form_state['values']['field_cabinetry_project_componen'][LANGUAGE_NONE] as $component_index => $cabinet_component) {
    if (is_numeric($component_index)) {
      $component_id = count($project->components);
      $component = new BasicEuroCabinet($component_id);
      $component->build($cabinet_component);
      $project->addComponent($component);
      dpm($project);
    }
  }
}

/**
 * Bootstrap cabinetry_cabinet_project object classes.
 */
function _cabinetry_cabinet_project_bootstrap() {
  spl_autoload_register(function ($class_name) {
    $filename = DRUPAL_ROOT . '/' . drupal_get_path('module', 'cabinetry_cabinet_project') . "/includes/Cabinetry/$class_name.inc";
    if (file_exists($filename)) {
      include "$filename";
    }
  });
}
